### ISSUE TITLE
MIUI12日用问题反馈

### ISSUE THREAD

**Issue by cdh1221** [Boos4721/updater#2]
The GPS direction is inverted (this seems to be a common problem of MIUI transplantation)
 Double-click the bright screen breath screen can not be used
 Internet speed display has always been 0.0 kb / s
 The breath display cannot be used (the breath display can only be displayed on the super wallpaper)
 So far, only found these bugs, daily use is no problem, thanks to the author, hard work

**Comment by Boos4721** [comment]
#busy for my exm
