### ISSUE TITLE
选择待升级的固件，点击刷写固件后，长时间无响应后，报错。

### ISSUE THREAD

**Issue by WayneShao** [Boos4721/updater#3]
![image](https://user-images.githubusercontent.com/13160811/132641118-d7f34d03-5598-4538-9269-ae45f53a3094.png)

**Comment by WayneShao** [comment]
![image](https://user-images.githubusercontent.com/13160811/132641354-d5923f2c-83cc-4055-a736-625a352430ef.png)
使用命令行升级也会卡死

**Comment by Boos4721** [comment]
之前busybox有bug的版本被你刷了 
> 回到官方固件的rootfs分区
`fw_setenv flag_last_success 0`
`fw_setenv flag_boot_rootfs 0`
`ubidetach -p /dev/mtd13`
然后正常ubi刷入回到rootfs_1分区即可
